name: Common CI setup
description: 'Sets up the environment for jobs during CI'

inputs:
  username_input:
    description: 'DockerHub login username'
    required: true
  password_input:
    description: 'DockerHub login password'
    required: true
  deployment_name:
    description: 'Target deployment to execute'
    required: true

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Extract main branch name
      if: inputs.deployment_name == 'production'
      id: extract_branch
      shell: bash
      run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

    - name: Extract Development pre-release branch name
      if: inputs.deployment_name == 'development'
      id: extract_features_branch
      shell: bash
      run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | sed 's/^dev\///')" >> $GITHUB_ENV

    - name: Set up Docker context for buildx
      id: buildx-context
      shell: bash
      run: |
        docker context create builders

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@master
      with:
        endpoint: builders
        version: latest

    - name: Login to DockerHub
      uses: docker/login-action@master
      with:
        username: ${{ inputs.username_input }}
        password: ${{ inputs.password_input }}

    - name: Cache Docker layers
      uses: actions/cache@v4
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-single-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-single-buildx

    - name: Prepare
      id: prep
      shell: bash
      run: |
        echo "image=dappforce/subsocial-web-app-grillchat:epicapp-${{ env.BRANCH_NAME }}-$(echo $GITHUB_SHA | head -c7)" >> $GITHUB_ENV
